baseURL = "https://in-toto.io"
languageCode = "en-us"
title = "in-toto"
pygmentsUseClasses = true
pygmentsCodefences = true
enableRobotsTXT = true
disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
description = "A framework to secure the integrity of software supply chains"
fontAwesomeVersion = "5.3.1"
vimeo_id = "237799749"
github_repo = "in-toto/community"

[params.logos]
navbar = "in-toto-horizontal-color.png"
hero = "in-toto-horizontal-color.png"
footer = "in-toto-stacked-white.png"

[[params.fonts]]
name = "Noto Sans"
sizes = [300,400,600,700]
type = "sans_serif"

[[params.features]]
title = "Software supply chain protection"
description = "Supply chain compromises are becoming a frequent occurrence. in-toto can help you protect your software supply chain."
button_url = "/in-toto"
button_text = "Read more"
img = "layout.png"

[[params.features]]
title = "Open, extensible standard"
description = "in-toto is an open metadata standard that you can implement in your software's supply chain toolchain."
button_url = "/specs"
button_text = "Read the specifications"
img = "metadata.png"

[[params.features]]
title = "Extensive tooling"
description = "You can use in-toto today by using our Apache-licensed libraries and tools."
button_url = "https://github.com/in-toto"
button_text = "Tools"
img = "gears.png"

[[menu.main]]
identifier = "about"
name = "About"
weight = 1

[[menu.main]]
parent = "about"
name = "What is in-toto?"
url = "/in-toto"
weight = 1

[[menu.main]]
parent = "about"
name = "Adoptions and Integrations"
url = "https://github.com/in-toto/friends"
weight = 2

[[menu.main]]
identifier = "community"
name = "Community"
weight = 2

[[menu.main]]
parent = "community"
name = "Contact"
url = "/contact"
weight = 1

[[menu.main]]
parent = "community"
name = "Contribute"
url = "https://github.com/in-toto/in-toto/"
weight = 2

[[menu.main]]
identifier = "get-started"
name = "Get started"
weight = 3

[[menu.main]]
parent = "get-started"
name = "Try it out"
url = "https://github.com/in-toto/demo"
weight = 1

[[menu.main]]
parent = "get-started"
name = "Metadata examples"
url = "/metadata-examples"
weight = 2

[[menu.main]]
parent = "get-started"
name = "Specifications"
url = "/specs"
weight = 3

[[menu.main]]
identifier = "learn"
name = "Learn more"
weight = 4

[[menu.main]]
parent = "learn"
name = "News"
url = "/news"
weight = 1

[[menu.main]]
parent = "learn"
name = "Security audit '23"
url = "/security-audit-23"
weight = 2

[[menu.main]]
parent = "learn"
name = "Frequently asked questions"
url = "/faq"
weight = 3


